### ISSUE TITLE
SmeartBot Defense Error

### ISSUE THREAD

**Issue by ichabod801** [ichabod801/t_games#376]
I'm getting this error from the defend method in tournaments:

```
Traceback (most recent call last):
  File "support_files\tourney_dummy.py", line 60, in <module>
    tournament(game_class, 'low-club', bot_classes)
  File "support_files\tourney_dummy.py", line 41, in tournament
    results = game.play()
  File "C:\Users\Craig\Documents\t_games\game.py", line 451, in play
    while self.player_action(self.players[self.player_index]):
  File "C:\Users\Craig\Documents\t_games\card_games\hearts_game.py", line 936, in player_action
    move = player.ask('What is your play? ')
  File "C:\Users\Craig\Documents\t_games\card_games\hearts_game.py", line 146, in ask
    card = str(self.play())
  File "C:\Users\Craig\Documents\t_games\card_games\hearts_game.py", line 443, in play
    return self.defend()
  File "C:\Users\Craig\Documents\t_games\card_games\hearts_game.py", line 341, in defend
    best_card = suit_cards[-1]
IndexError: list index out of range
```

**Comment by ichabod801** [comment]
The suit_cards list is card in the trick that match the suit lead. So this would seem to be an error when the bot is leading (there are no cards in the trick). But if there are no cards in trick, why are we not getting an error on line 340, which gets self.game.trick.cards[0]? Is there a problem with the iterator for cards.Hand? I can't see why there would be, it returns iter(self.cards). That should be fresh.

**Comment by ichabod801** [comment]
No, 340 wouldn't give an error in that case. If there are no cards, there's no looping, and that isn't checked. So it is for when they are starting the trick.

**Comment by ichabod801** [comment]
Ran a 1,234 game tournament of SmeartBots and HeartBots with no errors.
