### ISSUE TITLE
Calvin Cards fails with empty first command.

### ISSUE THREAD

**Issue by ichabod801** [ichabod801/t_games#437]
First command being blank (or I guess otherwise invalid) gives this error:

```
Traceback (most recent call last):
  File "test.py", line 75, in <module>
    test()
  File "test.py", line 66, in __call__
    self.menu.menu()
  File "C:\Users\Craig\Documents\t_games\interface.py", line 568, in menu
    self.handle_cmd(response)
  File "C:\Users\Craig\Documents\t_games\other_cmd.py", line 177, in handle_cmd
    return self.default(text)
  File "C:\Users\Craig\Documents\t_games\interface.py", line 220, in default
    self.do_play(line)
  File "C:\Users\Craig\Documents\t_games\interface.py", line 407, in do_play
    self.play_game(self.games[game_name], options)
  File "C:\Users\Craig\Documents\t_games\interface.py", line 586, in play_game
    results = self.game.play()
  File "C:\Users\Craig\Documents\t_games\game.py", line 495, in play
    while self.player_action(self.current_player):
  File "C:\Users\Craig\Documents\t_games\card_games\solitaire_games\calvin_cards_game.py", line 292, in player_action
    old_loc = self.moves[-1][1]
IndexError: list index out of range
```

**Comment by ichabod801** [comment]
The problem was that default was returning False on the error, as if a move was actually made.
