### ISSUE TITLE
Bug with Ten Thousand Zen Option

### ISSUE THREAD

**Issue by ichabod801** [ichabod801/t_games#495]
Playing with options = must-score straight=2000 zen=500. Got zen, and this error popped up:

```
Buckaroo rolled: 2, 2, 3, 3, 6, 6.
Buckaroo did not score with that roll.
How Zen.
Traceback (most recent call last):
...
  File "C:\Users\Craig\Documents\t_games\dice_games\ten_thousand_game.py", line 1178, in player_action
    if not self.do_roll(''):
  File "C:\Users\Craig\Documents\t_games\dice_games\ten_thousand_game.py", line 1007, in do_roll
    self.do_hold('')
  File "C:\Users\Craig\Documents\t_games\dice_games\ten_thousand_game.py", line 873, in do_hold
    counts = free.counts()
  File "C:\Users\Craig\Documents\t_games\dice.py", line 662, in counts
    counts = [0] * (max(self.dice[0].sides)  + 1)
IndexError: list index out of range

**Comment by ichabod801** [comment]
The zen option is working now, although it was really a problem with Pool.counts.
