### ISSUE TITLE
Option Question Fail with None Default

### ISSUE THREAD

**Issue by ichabod801** [ichabod801/t_games#576]
I tried starting Spider up by answering questions for the options. This is what happened:

```python
Should the deck only have one suit? y
Should the deck only have two suits? n
Should the tableau be dealt face up? n
Should you be able to turn over cards with empty lanes? y
Traceback (most recent call last):
...
  File "C:\Users\Craig\Documents\t_games\game.py", line 515, in play
    self.set_up()
  File "C:\Users\Craig\Documents\t_games\card_games\solitaire_games\solitaire_game.py", line 832, in set_up
    self.set_solitaire()
  File "C:\Users\Craig\Documents\t_games\card_games\solitaire_games\solitaire_game.py", line 1453, in set_solitaire
    self.deck = cards.MultiTrackingDeck(None, self, *options['deck-specs'])
TypeError: ABCMeta object argument after * must be an iterable, not NoneType
```

When I tried the same options from the command line (one-suit relaxed turn), it worked fine. Check the interaction of the one-suit and two-suit option questions.

**Comment by ichabod801** [comment]
It does appear to be a problem with the two options. If you say no to one suit and yes to two suits, it works fine.

**Comment by ichabod801** [comment]
Doing a find in files comes up with the following list of games using a default of None in an option:

* Liar's Dice (bot action)
* Pig (bot action)
* Prisoner's Dilemma (bot action)
* RPS
* Spider
* Yacht (key action)

So RPS, Spider, and Yacht would be the ones to test for this.

**Comment by ichabod801** [comment]
Changing ask_parameter is tricky. The default setting is separated from the take_action call. That's only relevant for Yacht. Do ask_bool first, then confirm there is a problem with the Yacht questions before messing with ask_parameter.

**Comment by ichabod801** [comment]
The new ask_bool is working in Spider. Test it in RPS (in 2.7) and in something else that doesn't have a None default.

**Comment by ichabod801** [comment]
The ask_bool is working in 2.7.

**Comment by ichabod801** [comment]
Boolean defaults test fine in Pig.

**Comment by ichabod801** [comment]
I have confirmed that it is a problem in Yacht.

**Comment by ichabod801** [comment]
Tested the fix for Yacht, and tested normal options in Mate.
